In [1]:
import pandas as pd

In [2]:
tr=pd.read_csv("E:/datasets/trainRF.csv")

In [3]:
tr.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [5]:
pd.set_option('display.max_columns',100)

In [6]:
tr.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,6,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,14,1208,1212,1411,8,2,15,1,1,0,1

In [7]:
tr.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [8]:
tr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.2 KB

In [10]:
from sklearn.model_selection import train_test_split
tr_train,tr_test=train_test_split(tr,test_size=0.2)

In [11]:
train_x=tr_train.iloc[:,0:-1]
train_y=tr_train.iloc[:,-1]
test_x=tr_test.iloc[:,0:-1]
test_y=tr_test.iloc[:,-1]

In [24]:
tr.shape

(2000, 21)

In [25]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(criterion='entropy',max_depth=9,
    min_samples_split=50,class_weight='balanced')

In [26]:
dt.fit(train_x,train_y)

DecisionTreeClassifier(class_weight='balanced', criterion='entropy',
                       max_depth=9, min_samples_split=50)

In [27]:
dt.predict(test_x)

array([3, 1, 3, 3, 2, 0, 2, 0, 1, 3, 0, 1, 0, 3, 3, 2, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 3, 2, 2, 1, 1, 0, 3, 3, 3, 1, 0, 1, 3, 3, 3, 3, 1, 0, 0,
       0, 2, 0, 3, 2, 1, 0, 1, 0, 1, 3, 3, 1, 0, 1, 1, 1, 2, 3, 3, 3, 3,
       1, 0, 2, 3, 2, 3, 2, 0, 1, 2, 1, 2, 1, 3, 0, 1, 1, 1, 3, 1, 3, 1,
       1, 1, 0, 2, 0, 0, 3, 3, 3, 1, 3, 2, 3, 1, 1, 1, 2, 3, 2, 1, 2, 3,
       3, 2, 1, 3, 2, 1, 1, 1, 0, 3, 0, 1, 1, 1, 1, 3, 0, 3, 0, 0, 3, 2,
       0, 2, 3, 3, 2, 1, 3, 0, 3, 3, 3, 1, 2, 2, 0, 0, 2, 1, 2, 3, 3, 1,
       0, 1, 0, 1, 2, 3, 2, 0, 2, 0, 3, 2, 2, 0, 1, 3, 1, 2, 3, 1, 1, 3,
       1, 1, 1, 0, 3, 0, 0, 1, 1, 0, 0, 1, 3, 0, 2, 0, 2, 3, 0, 0, 2, 2,
       1, 2, 3, 3, 3, 1, 1, 1, 3, 3, 0, 0, 0, 1, 1, 2, 1, 2, 2, 1, 1, 0,
       0, 3, 3, 3, 1, 1, 0, 1, 1, 1, 3, 3, 3, 0, 3, 1, 2, 3, 2, 3, 3, 1,
       0, 0, 1, 0, 2, 0, 1, 1, 2, 1, 2, 2, 0, 2, 3, 3, 0, 2, 2, 2, 1, 0,
       1, 3, 0, 1, 1, 3, 2, 2, 0, 2, 3, 2, 3, 2, 1, 1, 1, 3, 1, 0, 0, 2,
       0, 3, 2, 1, 0, 3, 0, 0, 2, 1, 1, 1, 1, 0, 2, 0, 3, 0, 0, 2, 3, 1,
       1, 1, 2, 1, 3, 2, 2, 2, 3, 1, 2, 3, 2, 1, 2, 1, 1, 0, 3, 2, 1, 2,
       0, 0, 1, 0, 3, 0, 0, 0, 2, 1, 0, 0, 0, 1, 3, 2, 2, 1, 3, 1, 2, 2,
       1, 1, 3, 1, 0, 0, 1, 2, 2, 3, 3, 0, 2, 3, 1, 0, 1, 1, 2, 2, 1, 2,
       2, 1, 1, 2, 1, 3, 1, 1, 1, 1, 1, 0, 0, 1, 0, 2, 1, 0, 2, 0, 1, 3,
       2, 2, 0, 3], dtype=int64)

In [28]:
from sklearn.metrics import confusion_matrix
tab1=confusion_matrix(test_y,dt.predict(test_x))
tab1

array([[87, 16,  0,  0],
       [ 6, 86, 11,  0],
       [ 0, 23, 65,  9],
       [ 0,  0, 11, 86]], dtype=int64)

In [29]:
tab1.diagonal().sum()/tab1.sum()

0.81

In [30]:
dt.feature_importances_

array([1.32253173e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.95437002e-17, 0.00000000e+00,
       1.88508648e-03, 0.00000000e+00, 7.73506688e-17, 3.35430093e-02,
       7.71986958e-02, 7.53156585e-01, 1.96345023e-03, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [31]:
feature_importance=pd.DataFrame({"Feature":train_x.columns,"Importance":dt.feature_importances_ })

In [32]:
feature_importance

          Feature    Importance
0   battery_power  1.322532e-01
1            blue  0.000000e+00
2     clock_speed  0.000000e+00
3        dual_sim  0.000000e+00
4              fc  0.000000e+00
5          four_g  0.000000e+00
6      int_memory  1.954370e-17
7           m_dep  0.000000e+00
8       mobile_wt  1.885086e-03
9         n_cores  0.000000e+00
10             pc  7.735067e-17
11      px_height  3.354301e-02
12       px_width  7.719870e-02
13            ram  7.531566e-01
14           sc_h  1.963450e-03
15           sc_w  0.000000e+00
16      talk_time  0.000000e+00
17        three_g  0.000000e+00
18   touch_screen  0.000000e+00
19           wifi  0.000000e+00

In [33]:
feature_importance.sort_values('Importance',ascending=False)

          Feature    Importance
13            ram  7.531566e-01
0   battery_power  1.322532e-01
12       px_width  7.719870e-02
11      px_height  3.354301e-02
14           sc_h  1.963450e-03
8       mobile_wt  1.885086e-03
10             pc  7.735067e-17
6      int_memory  1.954370e-17
7           m_dep  0.000000e+00
9         n_cores  0.000000e+00
1            blue  0.000000e+00
5          four_g  0.000000e+00
4              fc  0.000000e+00
3        dual_sim  0.000000e+00
2     clock_speed  0.000000e+00
15           sc_w  0.000000e+00
16      talk_time  0.000000e+00
17        three_g  0.000000e+00
18   touch_screen  0.000000e+00
19           wifi  0.000000e+00